language: python
python:
  - "3.6"
dist: xenial
cache: pip

git:
  depth: false

services:
  - docker

env:
  global:
    - CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver
    - CHROMIUM_BROWSER=/usr/bin/chromium-browser

script:
  - docker build .
  - sudo apt-get update
  - sudo apt-get install -y chromium-chromedriver
  - chromium-browser --version
  - which chromium-browser
  - ./test.sh