version: "3"

services:
  web:
    build: .
    volumes:
      - .:/work
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://postgres:example@postgres:5432/wharf
    depends_on:
      - postgres
  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: wharf
      POSTGRES_PASSWORD: example